name: rc car logger ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Build with PlatformIO
        run: pio run --environment wemos_d1_mini32
      - name: Build Filesystem Image
        run: pio run --target buildfs --environment wemos_d1_mini32
