name: upload-firmware-to-release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Build with PlatformIO
        run: pio run --environment wemos_d1_mini32
      - name: Build Filesystem Image
        run: pio run --target buildfs --environment wemos_d1_mini32
      - name: Upload Firmware Asset
        id: upload-firmware-image
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: ./.pio/build/wemos_d1_mini32/firmware.bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SPIFF Asset
        id: upload-filesystem-image
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: ./.pio/build/wemos_d1_mini32/spiffs.bin
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
